name=Adafruit WF100DPZ
version=1.0.0
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Arduino library for the WF100DPZ pressure sensor
paragraph=I2C driver for the WF100DPZ low-cost MEMS gauge pressure sensor with integrated temperature output.
category=Sensors
url=https://github.com/adafruit/Adafruit_WF100DPZ
architectures=*
depends=Adafruit BusIO
